# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Action Test

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Setting .env
        run: |
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> .env
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
          echo "NOTION_HISTORY_ID=${{ secrets.NOTION_HISTORY_ID }}" >> .env
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.workflow }}
          echo ${{ runner.name }}
          cat .env

      - name: Send To Notion
        run: |
          python send_to_notion.py ${{ job.status }}
