# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Notion To GitHub Pages

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Setting .env
        run: |
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> .env
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
          echo "NOTION_DATABSE_ID=${{ secrets.NOTION_DATABSE_ID }}" >> .env
          echo "NOTION_HOMEPAGE_ID=${{ secrets.NOTION_HOMEPAGE_ID }}" >> .env
          echo "NOTION_HISTORY_ID=${{ secrets.NOTION_HISTORY_ID }}" >> .env
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
          cat .env

      - name: Installing my packages
        run: npm install --legacy-peer-deps 

      - name: Build my App
        run: npm run gh_build && npm run gh_action_deploy

      - name: Deploy ðŸš€
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          COMMIT_NAME: ${{ github.repository_owner }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
      
      - name: Send To Notion
        run: |
          pip install python-dotenv
          python send_to_notion.py ${{ job.status }} "${{ github.workflow }}" ${{ github.run_number }}